from __future__ import annotations
from typing import Optional, List
import pandas as pd
from datetime import datetime


def _safe_val(row, col: str, default: float = 0.0) -> float:
    val = row.get(col)
    if val is None:
        return default
    try:
        return float(val)
    except (TypeError, ValueError):
        return default


def _format_hour(ts: pd.Timestamp, lang: str) -> str:
    if lang == "pl":
        return ts.strftime("%H:%M")
    return ts.strftime("%H:%M")


def build_text_forecast(
    df: pd.DataFrame,
    *,
    lang: str = "pl",
    city_name: Optional[str] = None,
    hours: int = 12,
) -> str:
    """
    Buduje mówioną prognozę na najbliższe `hours` godzin.
    Zwraca tekst, który można od razu puścić do TTS.
    """
    if df.empty:
        return "Brak danych prognozy." if lang == "pl" else "No forecast data available."

    # posortuj i przytnij
    df_sort = df.sort_index().iloc[:hours].copy()

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    place = city_name or ("wybranej lokalizacji" if lang == "pl" else "the selected location")

    lines: List[str] = []

    if lang == "pl":
        lines.append(f"Prognoza pogody dla {place}, stan na {now}.")
    else:
        lines.append(f"Weather forecast for {place}, issued at {now}.")

    # pogrupuj po dacie, żeby tekst był bardziej naturalny
    df_sort["date"] = df_sort.index.date
    for day, day_df in df_sort.groupby("date"):
        day_name = day.strftime("%Y-%m-%d")
        if lang == "pl":
            lines.append(f"Dzień {day_name}:")
        else:
            lines.append(f"On {day_name}:")

        for ts, row in day_df.iterrows():
            temp = _safe_val(row, "temperature_c", default=0.0)
            precip = _safe_val(row, "precip_mm", default=0.0)
            hour = _format_hour(ts, lang)

            if lang == "pl":
                sentence = f"O {hour} około {temp:.1f} stopnia Celsjusza."
                if precip > 2.0:
                    sentence += f" Przewidywany opad około {precip:.1f} milimetra."
                elif 0 < precip <= 2.0:
                    sentence += " Możliwy słaby opad."
            else:
                sentence = f"At {hour}, about {temp:.1f} degrees Celsius."
                if precip > 2.0:
                    sentence += f" Expected precipitation around {precip:.1f} millimeters."
                elif 0 < precip <= 2.0:
                    sentence += " Light precipitation possible."

            lines.append(sentence)

    # stopka
    if lang == "pl":
        lines.append("Prognoza wygenerowana automatycznie przez moduł AI platformy pogodowej.")
    else:
        lines.append("Forecast automatically generated by the platform's AI module.")

    # sklej w jeden tekst – TTS lub UI textarea
    return " ".join(lines)
