from __future__ import annotations
import pandas as pd
from datetime import datetime

def build_text_forecast(df: pd.DataFrame, lang: str = "pl", city_name: str | None = None) -> str:
    if df.empty:
        return "Brak danych prognozy."
    df_sort = df.sort_index().iloc[:12]
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    place = city_name or "wybranej lokalizacji"

    if lang == "pl":
        parts = [f"Prognoza pogody dla {place}, stan na {now}."]
        for ts, row in df_sort.iterrows():
            temp = row.get("temperature_c")
            precip = row.get("precip_mm")
            hour = ts.strftime("%H:%M")
            desc = f"O godzinie {hour} temperatura około {temp:.1f} °C."
            if precip and precip > 0:
                desc += f" Możliwe opady: {precip:.1f} mm."
            parts.append(desc)
        parts.append("Prognoza wygenerowana przez moduł AI platformy pogodowej.")
        return " ".join(parts)
    else:
        parts = [f"Weather forecast for {place}, valid at {now}."]
        for ts, row in df_sort.iterrows():
            temp = row.get("temperature_c")
            precip = row.get("precip_mm")
            hour = ts.strftime("%H:%M")
            desc = f"At {hour} the temperature will be about {temp:.1f} °C."
            if precip and precip > 0:
                desc += f" Possible precipitation: {precip:.1f} mm."
            parts.append(desc)
        parts.append("Forecast generated by the platform AI module.")
        return " ".join(parts)
